name: volcano
channels:
  - pyviz/label/dev
  - pyviz
  - bokeh
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bokeh=1.3.4
  - holoviews=1.13
  - hvplot=0.5.1
  - ipykernel=5.1.2
  - jupyter_client=5.3
  - jupyter_core=4.5
  - matplotlib=3.1
  - notebook=6.0
  - numpy=1.17
  - pandas=0.25.
  - python=3.7
  - tornado=5.1.1